export default {
  SPLASHIMAGE: require('../assets/images/SplashImage.png'),
  LOADER: require('../assets/images/Loader.png'),
  APPLOGO: require('../assets/images/AppLogo.png'),
  CALENDERINACTIVE: require('../assets/images/CalendarInactive.png'),
  CALENDERACTIVE: require('../assets/images/CalendarActive.png'),
  CALENDERICON: require('../assets/images/CalenderIcon.png'),
  DOCTORIMAGE: require('../assets/images/DoctorImage.png'),
  DOCUMENTACTIVE: require('../assets/images/DocumentActive.png'),
  DOCUMENTINACTIVE: require('../assets/images/DocumentInactive.png'),
  DRAWERICON: require('../assets/images/DrawerIcon.png'),
  HOMEACTIVE: require('../assets/images/HomeActive.png'),
  HOMEINACTIVE: require('../assets/images/HomeInactive.png'),
  MESSAGEICON: require('../assets/images/MessageIcon.png'),
  MICICON: require('../assets/images/MicIcon.png'),
  QUESTIONICON: require('../assets/images/QuestionIcon.png'),
  REMINDERICON: require('../assets/images/ReminderIcon.png'),
  UPLOADACTIVE: require('../assets/images/UploadActive.png'),
  UPLOADINACTIVE: require('../assets/images/UploadInactive.png'),
  VITAMINIMAGE: require('../assets/images/VitaminImage.png'),
  BACKBUTTONIMAGE: require('../assets/images/backButton.png'),
  LINKICON: require('../assets/images/linkIcon.png'),
  LOCATIONICON: require('../assets/images/locationIcon.png'),
  UPLOADICON: require('../assets/images/uploadIcon.png'),
  UPLOADIMAGE1: require('../assets/images/uploadImage1.png'),
  UPLOADIMAGE2: require('../assets/images/uploadImage2.png'),
};
